-- Check out the Top 10 City by Revenue and Number of Films Released

SELECT CT.CITY,
	SUM(P.AMOUNT) AS REVENUE,
	COUNT(DISTINCT F.FILM_ID) AS NO_OF_FILM_RELEASED
FROM CITY CT
JOIN ADDRESS ADD ON ADD.CITY_ID = CT.CITY_ID
JOIN CUSTOMER C ON C.ADDRESS_ID = ADD.ADDRESS_ID
JOIN RENTAL R ON R.CUSTOMER_ID = C.CUSTOMER_ID
JOIN INVENTORY I ON I.INVENTORY_ID = R.INVENTORY_ID
JOIN PAYMENT P ON P.RENTAL_ID = R.RENTAL_ID
JOIN FILM F ON F.FILM_ID = I.FILM_ID
GROUP BY CT.CITY
ORDER BY REVENUE DESC
LIMIT 10;