-- Check out the customers who made the highest expenditures on DVD rentals and 
-- how many times they rented DVDs
SELECT C.FIRST_NAME AS CUSTOMER,
	SUM(P.AMOUNT) AS PAYMENT_AMOUNT,
	COUNT(P.RENTAL_ID) AS DVD_RENTAL_QUANTITY
FROM PAYMENT P
JOIN CUSTOMER C ON P.CUSTOMER_ID = C.CUSTOMER_ID
JOIN ADDRESS AD ON C.ADDRESS_ID = AD.ADDRESS_ID
JOIN CITY CT ON CT.CITY_ID = AD.CITY_ID
JOIN COUNTRY CN ON CN.COUNTRY_ID = CT.COUNTRY_ID
GROUP BY C.FIRST_NAME
ORDER BY PAYMENT_AMOUNT DESC, DVD_RENTAL_QUANTITY DESC