-- Check out which year produced the Greatest Film Revenue

SELECT F.RELEASE_YEAR,
	SUM(P.AMOUNT)
FROM PAYMENT P
JOIN RENTAL R ON R.RENTAL_ID = P.RENTAL_ID
JOIN INVENTORY I ON I.INVENTORY_ID = R.INVENTORY_ID
JOIN FILM F ON F.FILM_ID = I.FILM_ID
GROUP BY F.RELEASE_YEAR
ORDER BY F.RELEASE_YEAR DESC