-- Check out which films are frequently rent out,and the rental duration

SELECT F.TITLE,
	EXTRACT(DAY
									FROM(RETURN_DATE - RENTAL_DATE)) AS RENTAL_DAY,
	COUNT(P.CUSTOMER_ID) AS NO_OF_RENTALS
FROM FILM F
JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID
JOIN RENTAL R ON R.INVENTORY_ID = I.INVENTORY_ID
LEFT JOIN PAYMENT P ON P.RENTAL_ID = R.RENTAL_ID
GROUP BY F.TITLE,
	RENTAL_DAY
ORDER BY NO_OF_RENTALS DESC