-- Check out which category has the highest inventory of films, and how many films are in that category?

SELECT F.TITLE,
	C.NAME AS CATEGORY_NAME,
	COUNT(1) AS INVENTORY_QUANTITY
FROM FILM F
JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
JOIN CATEGORY C ON C.CATEGORY_ID = FC.CATEGORY_ID
JOIN INVENTORY I ON I.FILM_ID = FC.FILM_ID
JOIN RENTAL R ON R.INVENTORY_ID = I.INVENTORY_ID
GROUP BY F.TITLE,
	C.NAME
ORDER BY INVENTORY_QUANTITY DESC