-- Check out the Top 10 Countries by Revenue and Number of Films Released 
SELECT CN.COUNTRY,
	SUM(P.AMOUNT) AS REVENUE,
	COUNT(F.FILM_ID) AS NO_OF_FILM_RELEASED
FROM COUNTRY CN
JOIN CITY CT ON CN.COUNTRY_ID = CT.COUNTRY_ID
JOIN ADDRESS ADD ON ADD.CITY_ID = CT.CITY_ID
JOIN CUSTOMER C ON C.ADDRESS_ID = ADD.ADDRESS_ID
JOIN RENTAL R ON R.CUSTOMER_ID = C.CUSTOMER_ID
JOIN INVENTORY I ON I.INVENTORY_ID = R.INVENTORY_ID
JOIN PAYMENT P ON P.RENTAL_ID = R.RENTAL_ID
JOIN FILM F ON F.FILM_ID = I.FILM_ID
GROUP BY CN.COUNTRY
ORDER BY REVENUE DESC
LIMIT 10;